### ISSUE TITLE
imgFixHeight in assets/js/concat/main.js

### ISSUE THREAD

**Issue by libbeydesign** [zackphilipps/scratch-theme#6]
Images added to the site are being resized disproportionately when this portion of main.js is active. In screenshot example, the original is 116px high (and height/weight properties are defined), but overridden with style="height: 95px;". Deactivating this portion of main.js resolves the issue.

![screen shot 2016-09-03 at 2 23 21 pm](https://cloud.githubusercontent.com/assets/8962801/18226900/fe4d2bb6-71e1-11e6-8ad5-6cb6ed51ed4a.png)

**Comment by zoephilipps** [comment]
@libbeydesign 👋 

https://github.com/zackphilipps/scratch-theme/releases/tag/v1.6.7 has a fix, but be aware that I also changed all the directory names since the underscores were causing problems on certain hosts. (Really all you have to do is delete `assets/core/js/gutenberg.js`)

I've also opened an issue for Gutenberg here: https://github.com/matejlatin/Gutenberg/issues/51

Thanks for bringing this to my attention!
